version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/user/Documents/github/grpcwallet/mongodb/database
    ports:
    - 27010:27017
    restart: unless-stopped